### ISSUE TITLE
should  '--server-nodes' be '--server_nodes'  in dmlc_yarn.py?

### ISSUE THREAD

**Issue by RockWater** [CNevd/Difacto_DMLC#10]
for the line 32 in  Difacto_DMLC/dmlc-core/tracker/dmlc_yarn.py ,
should '--server-nodes' be '--server_nodes' ?

**Comment by CNevd** [comment]
@RockWater both can be ok

**Comment by RockWater** [comment]
@CNevd  Txs.  By the way, how to get the key id from the original feature id by some hashing trick ?  Would like to get the pair of (feature id ,value ) rather than (key ,value) as exported by the model.

**Comment by CNevd** [comment]
@RockWater  check [issues8](https://github.com/CNevd/Difacto_DMLC/issues/8)
you can use `-max_key` if you know your max key of feature id or write a inverse function for ReverseBytes in `dump.cc` as @Lisz1024 did :)

**Comment by qian2729** [comment]
Writeed InverseBytes according to ReverseBytes
`inline uint64_t InverseBytes(uint64_t x) {
          x = (x & 0x0F0F0F0F0F0F0F0FULL) << 4 |
              (x & 0xF0F0F0F0F0F0F0F0ULL) >> 4;
          x = (x & 0x00FF00FF00FF00FFULL) << 8 |
              (x & 0xFF00FF00FF00FF00ULL) >> 8;
          x = (x & 0x0000FFFF0000FFFFULL) << 16 |
              (x & 0xFFFF0000FFFF0000ULL) >> 16;
          x = x << 32 | x >> 32;
          return x;
}`
-- ignore this, we can just using  ReverseBytes funtion again to inverse.

**Comment by CNevd** [comment]
@qian2729 great job!  Could you send a pr for this?

**Comment by RockWater** [comment]
@CNevd  @qian2729 many thanks.

**Comment by qian2729** [comment]
@CNevd @RockWater  In fact, we don't need to write new inverse bytes function to remap new feature id to original feature id, just using ReverseBytes function(at src/base/localizer.h) at new feature id again, we can got the original feature id. [Tested]

**Comment by CNevd** [comment]
dump,cc has supported inverse bytes function, will close this issue
