### ISSUE TITLE
Difacto_DMLC's installation become Wrong

### ISSUE THREAD

**Issue by qichaotang** [CNevd/Difacto_DMLC#12]
root@hadoop-master:~/Difacto_DMLC/src/difacto# make
g++ -O3 -ggdb -Wall -std=c++11 -I./ -I../ -I../../ps-lite/src -I../../dmlc-core/include -I../../dmlc-core/src -I../../ps-lite/deps/include -fopenmp -fPIC -DDMLC_USE_HDFS=0                                    -DDMLC_USE_S3=0 -DDMLC_USE_GLOG=1 -DDMLC_USE_AZURE=0   build/config.pb.o build/difacto.o ../../dmlc-core/libdmlc.a ../../ps-lite/build/libps.a -fopenmp -lrt ../../ps-lite/deps/lib/libglog.a ../../ps-lite/deps/lib/libprotobuf.a ../../ps-lite/deps/lib/libgflags.a ../../ps-lite/deps/lib/libzmq.a ../../ps-lite/deps/lib/libcityhash.a ../../ps-lite/deps/lib/liblz4.a -lgssapi_krb5  -o build/difacto.dmlc
../../dmlc-core/libdmlc.a(hdfs_filesys.o): In function `dmlc::io::HDFSFileSystem::~HDFSFileSystem()':
hdfs_filesys.cc:(.text+0xba): undefined reference to `hdfsDisconnect'
../../dmlc-core/libdmlc.a(hdfs_filesys.o): In function `dmlc::io::HDFSFileSystem::Open(dmlc::io::URI const&, char const*, bool)':
hdfs_filesys.cc:(.text+0x6a0): undefined reference to `hdfsOpenFile'
../../dmlc-core/libdmlc.a(hdfs_filesys.o): In function `dmlc::io::HDFSFileSystem::GetPathInfo(dmlc::io::URI const&)':
hdfs_filesys.cc:(.text+0x16df): undefined reference to `hdfsGetPathInfo'
hdfs_filesys.cc:(.text+0x1cbd): undefined reference to `hdfsFreeFileInfo'
../../dmlc-core/libdmlc.a(hdfs_filesys.o): In function `dmlc::io::HDFSFileSystem::HDFSFileSystem()':
hdfs_filesys.cc:(.text+0x27e1): undefined reference to `hdfsConnect'
../../dmlc-core/libdmlc.a(hdfs_filesys.o): In function `dmlc::io::HDFSFileSystem::ListDirectory(dmlc::io::URI const&, std::vector<dmlc::io::FileInfo, std::allocator<dmlc::io::FileInfo> >*)':
hdfs_filesys.cc:(.text+0x2d5a): undefined reference to `hdfsListDirectory'
hdfs_filesys.cc:(.text+0x3419): undefined reference to `hdfsFreeFileInfo'
../../dmlc-core/libdmlc.a(hdfs_filesys.o): In function `dmlc::io::HDFSStream::~HDFSStream()':
hdfs_filesys.cc:(.text._ZN4dmlc2io10HDFSStreamD2Ev[_ZN4dmlc2io10HDFSStreamD5Ev]+0x41): undefined reference to `hdfsCloseFile'
hdfs_filesys.cc:(.text._ZN4dmlc2io10HDFSStreamD2Ev[_ZN4dmlc2io10HDFSStreamD5Ev]+0xa2): undefined reference to `hdfsDisconnect'
../../dmlc-core/libdmlc.a(hdfs_filesys.o): In function `dmlc::io::HDFSStream::Read(void*, unsigned long)':
hdfs_filesys.cc:(.text._ZN4dmlc2io10HDFSStream4ReadEPvm[_ZN4dmlc2io10HDFSStream4ReadEPvm]+0x55): undefined reference to `hdfsRead'
../../dmlc-core/libdmlc.a(hdfs_filesys.o): In function `dmlc::io::HDFSStream::Write(void const*, unsigned long)':
hdfs_filesys.cc:(.text._ZN4dmlc2io10HDFSStream5WriteEPKvm[_ZN4dmlc2io10HDFSStream5WriteEPKvm]+0x5e): undefined reference to `hdfsWrite'
../../dmlc-core/libdmlc.a(hdfs_filesys.o): In function `dmlc::io::HDFSStream::Seek(unsigned long)':
hdfs_filesys.cc:(.text._ZN4dmlc2io10HDFSStream4SeekEm[_ZN4dmlc2io10HDFSStream4SeekEm]+0x2e): undefined reference to `hdfsSeek'
../../dmlc-core/libdmlc.a(hdfs_filesys.o): In function `dmlc::io::HDFSStream::Tell()':
hdfs_filesys.cc:(.text._ZN4dmlc2io10HDFSStream4TellEv[_ZN4dmlc2io10HDFSStream4TellEv]+0x2b): undefined reference to `hdfsTell'
collect2: error: ld returned 1 exit status
make: *** [build/difacto.dmlc] Error 1

**Comment by CNevd** [comment]
try set USE_HDFS=1 in https://github.com/CNevd/Difacto_DMLC/blob/master/dmlc-core/make/config.mk#L22 and https://github.com/CNevd/Difacto_DMLC/blob/master/ps-lite/make/config.mk#L13

**Comment by qichaotang** [comment]
Thanks,it built successful!!!
