### ISSUE TITLE
sh run_local.sh  become Wrong!!!

### ISSUE THREAD

**Issue by qichaotang** [CNevd/Difacto_DMLC#13]
root@hadoop-master:~/Difacto_DMLC/src/linear# sh run_local.sh 
2016-11-16 15:27:54,784 INFO start listen on 172.18.0.2:9091
build/linear.dmlc: error while loading shared libraries: libhdfs.so.0.0.0: cannot open shared object file: No such file or directory
build/linear.dmlc: error while loading shared libraries: libhdfs.so.0.0.0: cannot open shared object file: No such file or directory
build/linear.dmlc: error while loading shared libraries: libhdfs.so.0.0.0: cannot open shared object file: No such file or directory
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/Difacto_DMLC/dmlc-core/tracker/tracker.py", line 345, in <lambda>
    self.thread = Thread(target = (lambda : subprocess.check_call(self.cmd, env=env, shell=True)), args = ())
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'build/linear.dmlc guide/demo.conf ' returned non-zero exit status 127

build/dump.dmlc: error while loading shared libraries: libhdfs.so.0.0.0: cannot open shared object file: No such file or directory

**Comment by qichaotang** [comment]
I use hadoop cluster by docker,I try some times,this wrong appear

**Comment by CNevd** [comment]
try build with `USE_HDFS=0` if use local model?

**Comment by qichaotang** [comment]
I try build with USE_HDFS=0 in config.mk,but while I use make,it become "make: Nothing to be done for `all'."

**Comment by qichaotang** [comment]
local model is successful!!!
I try build with USE_HDFS=1 while use yarn model

**Comment by CNevd** [comment]
great!  BTW try `make clean;make` when "make: Nothing to be done for `all'."
