### ISSUE TITLE
dump bug

### ISSUE THREAD

**Issue by toughJack** [CNevd/Difacto_DMLC#14]
when I run the command "build/dump.dmlc model_in="agaricus_model_part-0" dump_out="dump.txt" need_inverse", it reports the following error:
[
<img width="880" alt="2016-11-18 7 06 36" src="https://cloud.githubusercontent.com/assets/3960162/20428077/32bd92d4-adc2-11e6-8c5f-35ce05836456.png">

Can anyone help me ?

**Comment by CNevd** [comment]
could you post ur agaricus_model_part-0?

**Comment by toughJack** [comment]
the dump problem has been solved.
but i got a new problem about 'run_yarn.sh'. when i run this script, the application failed. the error log is like this:
<img width="1029" alt="2016-11-22 1 12 30" src="https://cloud.githubusercontent.com/assets/3960162/20492716/d00b34a2-b050-11e6-8a2a-cecec033a484.png">

<img width="1104" alt="2016-11-22 1 08 41" src="https://cloud.githubusercontent.com/assets/3960162/20492633/6eaa1d86-b050-11e6-92ce-37c77d4aaec3.png">
it seems to be related with java version, but i do not know how to fix this.
