### ISSUE TITLE
problem when model file have more than one part

### ISSUE THREAD

**Issue by muyinanhai** [CNevd/Difacto_DMLC#16]
when the model files are more than one parts, it goes wrong when predicting

**Comment by CNevd** [comment]
can you post the error ?

**Comment by muyinanhai** [comment]
F0321 10:16:26.843240 56820 async_sgd.h:160] Check failed: fi->Read(&sq_cum_grad, sizeof(float)) == sizeof(float) (0 vs. 4) 
*** Check failure stack trace: ***
    @           0x498b9a  google::LogMessage::Fail()
    @           0x49aacf  google::LogMessage::SendToLog()
    @           0x49877f  google::LogMessage::Flush()
    @           0x49b40e  google::LogMessageFatal::~LogMessageFatal()
    @           0x417dfd  dmlc::linear::FTRLEntry::Load()
    @           0x42ccd6  ps::KVStoreSparseST<>::Load()
    @           0x43ba04  dmlc::linear::AsgdServer::LoadModel()
    @           0x43d84c  dmlc::solver::IterServer::ProcessRequest()
    @           0x47290c  ps::Executor::ProcessActiveMsg()
    @           0x476258  ps::Executor::Run()
    @     0x7fc6fa78ba60  (unknown)
    @     0x7fc6f9d99184  start_thread
    @     0x7fc6f9ac637d  clone
bash: line 9: 56816 Aborted                 (core dumped) build/linear.dmlc guide/demo_predict.conf
bash: line 9: 56797 Killed                  build/linear.dmlc guide/demo_predict.conf
bash: line 9: 56798 Killed                  build/linear.dmlc guide/demo_predict.conf


There are two parts of my model file named agaricus_model_part-0 and agaricus_model_part-1.
When I merge two of the files, it works.

**Comment by CNevd** [comment]
the num of servers is 2 ?
if you want to load 2 parts of model you need to set -s 2

**Comment by muyinanhai** [comment]
Yes, the num of server is 2

**Comment by CNevd** [comment]
try retrain you model file:)  there may be something wrong with your model

**Comment by muyinanhai** [comment]
seems that when predicting, the param "ALGO" also should be set
