### ISSUE TITLE
New function is needed

### ISSUE THREAD

**Issue by muyinanhai** [CNevd/Difacto_DMLC#17]
When predict, we only get the proba, but we don't get the original samples.
for example:
y1 x11 x12   (sample 1)
y2 x21 x22   (sample 2)

we then get 
predict_y1
predict_y2

but we don't know predict_y1 belongs to the prediction result of sample 1 or sample 2.

**Comment by CNevd** [comment]
A simple way is to do the prediction with only 1 worker to ensure the order of outputs be consistent with ur inputs

**Comment by muyinanhai** [comment]
while, as described in [criteo_kaggle](http://wormhole.readthedocs.io/en/latest/tutorial/criteo_kaggle.html)

_Then the i-th line of pred.txt will contains the prediction p=⟨w,x⟩p=⟨w,x⟩ for be i-th example (line) in test.txt_
 But I'm still not so sure about it

**Comment by CNevd** [comment]
u can test it with a small dataset :)
or some ext-info for each sample (eg: pvid) can be also provided when predicting with changing the code in dmlc-core which is a little professional

**Comment by muyinanhai** [comment]
Solved it. I used the method as describe before.
