### ISSUE TITLE
example about run linear on yarn

### ISSUE THREAD

**Issue by formath** [CNevd/Difacto_DMLC#2]
Can someone give a example about how to run linear on yarn?

**Comment by CNevd** [comment]
@formath  src/linear/run_yarn.sh  is not ok?

**Comment by formath** [comment]
@CNevd  I can't find "guide/demo_hdfs.conf" in run_yarn.sh. Is this configure file the hdfs-site.conf?

**Comment by CNevd** [comment]
@formath guide/demo_hdfs.conf is generated by
`cat <<< "
train_data = \"hdfs://${hdfs_dir}/data/agaricus.txt.train\"
val_data = \"hdfs://${hdfs_dir}/data/agaricus.txt.test\"
max_data_pass = 3
" >guide/demo_hdfs.conf`
or you can write your own  .conf

**Comment by formath** [comment]
@CNevd Yeah. It's simple to use. But I still want to know could linear in this project support millions features and instances? If based on ps-lite, I think it will be.

**Comment by CNevd** [comment]
yes, it supports, we use linear and difacto for millions features and 10~100 millions instances

**Comment by formath** [comment]
@CNevd Great job. The original project of difacto does't support distributed training. Is this project support that? What is the main difference against the original project?

**Comment by CNevd** [comment]
it supports distributed training， this project is extract from wormhole/learn/difacto which is the first version of difacto
