### ISSUE TITLE
run_yarn.sh fail: Timeout (500 sec) to wait all other nodes initialized. See commmets for more information

### ISSUE THREAD

**Issue by alaleiwang** [CNevd/Difacto_DMLC#20]
command is : ../../dmlc-core/tracker/dmlc_yarn.py --queue users.bigdata   --hadoop_binary /opt/cloudera/parcels/CDH/bin/hadoop --vcores 1 -n 2 -s 1 build/linear.dmlc guide/demo_hdfs.conf

error log:
Container: container_1504869490009_0132_01_000006 on cdh246.test_8041
=======================================================================
LogType:stderr
Log Upload Time:Fri Sep 15 12:23:24 +0800 2017
LogLength:606
Log Contents:
F0915 12:14:57.163543  2300 manager.cc:55] Timeout (500 sec) to wait all other nodes initialized. See commmets for more information
*** Check failure stack trace: ***
    @           0x496a2a  google::LogMessage::Fail()
    @           0x4988f2  google::LogMessage::SendToLog()
    @           0x49660f  google::LogMessage::Flush()
    @           0x49920e  google::LogMessageFatal::~LogMessageFatal()
    @           0x47daf2  ps::Manager::Run()
    @           0x475339  ps::Postoffice::Run()
    @           0x408381  main
    @     0x7f3bdc936b15  __libc_start_main
    @           0x40a481  (unknown)

LogType:stdout
Log Upload Time:Fri Sep 15 12:23:24 +0800 2017
LogLength:75
Log Contents:
===============================argv: ['./linear.dmlc', './demo_hdfs.conf']

**Comment by CNevd** [comment]
First check if all logs are normal. In default the logs are avaialable at /tmp/, you can specify the log directory by "-log_dir your_log_dir". If everything goes fine, then probably it's due to the cluster resource manager (such as yarn) is slow to start the jobs. You can increase the sync timeout value, such as waiting 1000 sec:  "-sync_timeout 1000"

**Comment by alaleiwang** [comment]
yarn resource is enough,i can see many attempt failure....

can ./build/linear.dmlc guide/demo_hdfs.conf be run singly?

if i just run ./build/linear.dmlc guide/demo_hdfs.conf,it showes the same error:
./build/linear.dmlc guide/demo_hdfs.conf
F0915 14:12:11.437660 27440 manager.cc:55] Timeout (500 sec) to wait all other nodes initialized. See commmets for more information
*** Check failure stack trace: ***
    @           0x496a2a  google::LogMessage::Fail()
    @           0x4988f2  google::LogMessage::SendToLog()
    @           0x49660f  google::LogMessage::Flush()
    @           0x49920e  google::LogMessageFatal::~LogMessageFatal()
    @           0x47daf2  ps::Manager::Run()
    @           0x475339  ps::Postoffice::Run()
    @           0x408381  main
    @     0x7f46eb297b15  __libc_start_main
    @           0x40a481  (unknown)
Aborted

what does this mean?

**Comment by CNevd** [comment]
did you try to increase the sync timeout value?   it means some nodes are not ready to run see ```ps-lite/src/system/manager.cc``` for details

**Comment by alaleiwang** [comment]
i can't use -sync_timeout:
../../dmlc-core/tracker/dmlc_yarn.py --queue users.bigdata --hadoop_binary /opt/cloudera/parcels/CDH/bin/hadoop --vcores 1 -n 2 -s 1 -sync_timeout 1000  build/linear.dmlc guide/demo_hdfs.conf1 
usage: dmlc_yarn.py [-h] -n NWORKER [-hip HOST_IP] [-s SERVER_NODES]
                    [--log-level {INFO,DEBUG}] [--log-file LOG_FILE]
                    [-q QUEUE] [-ac {0,1}] [-f FILES] [--jobname JOBNAME]
                    [--tempdir TEMPDIR] [--vcores VCORES] [-mem MEMORY_MB]
                    [--libhdfs-opts LIBHDFS_OPTS] [--name-node NAME_NODE]
                    [--ship-libcxx SHIP_LIBCXX]
                    [--app-classpath APP_CLASSPATH] [--env ENV]
                    [--yarn-scripts YARN_SCRIPTS]
                    [--max-attempts MAX_ATTEMPTS]
                    command [command ...]
dmlc_yarn.py: error: argument -s/--server-nodes: invalid int value: 'ync_timeout'

**Comment by alaleiwang** [comment]
all /tmp/linear.dmlc.xxxxx log showes like:
[@cdh247.test ~]# cat /tmp/linear.dmlc.S_10.2.177.247_38357.log.INFO.20170915-150834.20753 
Log file created at: 2017/09/15 15:08:34
Running on machine: cdh247.test
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0915 15:08:34.604833 20753 van.cc:30] I'm [role: SERVER id: "S_10.2.177.247_38357" hostname: "10.2.177.247" port: 38357]
W0915 15:08:54.587877 20756 manager.cc:278] the scheduler is died, exit

[@cdh247.test ~]# cat /tmp/linear.dmlc.S_10.2.177.247_38357.log.WARNING.20170915-150854.20753
Log file created at: 2017/09/15 15:08:54
Running on machine: cdh247.test
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
W0915 15:08:54.587877 20756 manager.cc:278] the scheduler is died, exit

**Comment by CNevd** [comment]
```build/linear.dmlc guide/demo_hdfs.conf1 --sync_timeout 1000```

**Comment by alaleiwang** [comment]
[@cdh240.test /opt/alalei/Difacto_DMLC/src/linear]$ build/linear.dmlc guide/demo_hdfs.conf1 --sync_timeout 1000






F0915 15:38:46.669119 16688 manager.cc:55] Timeout (1000 sec) to wait all other nodes initialized. See commmets for more information
*** Check failure stack trace: ***
    @           0x496a2a  google::LogMessage::Fail()
    @           0x4988f2  google::LogMessage::SendToLog()
    @           0x49660f  google::LogMessage::Flush()
    @           0x49920e  google::LogMessageFatal::~LogMessageFatal()
    @           0x47daf2  ps::Manager::Run()
    @           0x475339  ps::Postoffice::Run()
    @           0x408381  main
    @     0x7faccb29fb15  __libc_start_main
    @           0x40a481  (unknown)
Aborted

**Comment by CNevd** [comment]
sorry I mean ```../../dmlc-core/tracker/dmlc_yarn.py --queue users.bigdata --hadoop_binary /opt/cloudera/parcels/CDH/bin/hadoop --vcores 1 -n 2 -s 1 -sync_timeout 1000 build/linear.dmlc guide/demo_hdfs.conf1 --sync_timeout 1000```

**Comment by alaleiwang** [comment]
i tried.... the same error 

more to be added,do it support viewfs？
sometime i can see errors in yarn logs（but not always...）：
[15:43:45] src/io/hdfs_filesys.cc:132: =======================hdfsfile: %shdfs://nameservice1/user/alalei/output/data/agaricus.txt.train
hdfsGetPathInfo(hdfs://nameservice1/user/alalei/output/data/agaricus.txt.train): getFileInfo error:
java.lang.IllegalArgumentException: Wrong FS: hdfs://nameservice1/user/alalei/output/data/agaricus.txt.train, expected: viewfs://cluster21/
        at org.apache.hadoop.fs.FileSystem.checkPath(FileSystem.java:662)
        at org.apache.hadoop.fs.viewfs.ViewFileSystem.getUriPath(ViewFileSystem.java:117)
        at org.apache.hadoop.fs.viewfs.ViewFileSystem.getFileStatus(ViewFileSystem.java:346)
        at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1417)
[15:43:45] include/dmlc/logging.h:208: [15:43:45] src/io/hdfs_filesys.cc:135: Check failed: info != NULL Path do not exist:hdfs://nameservice1/user/alalei/output/data/agaricus.txt.train
terminate called after throwing an instance of 'dmlc::Error'
  what():  [15:43:45] src/io/hdfs_filesys.cc:135: Check failed: info != NULL Path do not exist:hdfs://nameservice1/user/alalei/output/data/agaricus.txt.train

to be noticed:
i change the core-site.xml on the client,defaultFS value from viewfs:// to hdfs://
but when container running on remote node,where hadoop conf default to use viewfs,so the above error  showed

i know if i can upload client core-site.xml(with defaultFS defined in hdfs:// mode),i can fix the problem
but the question is dmlc-yarn.py seems has't option like "--file" or "--archives" to help get confs uploaded to the hdfs distributed cache

**Comment by alaleiwang** [comment]
i make some code change for dmlc-core,ant it finally work fine....
thanks a lot

**Comment by CNevd** [comment]
nice

**Comment by wangke19910912** [comment]
@alaleiwang ,hi,what change did you do for this error?

**Comment by Carl-Hee** [comment]
@alaleiwang I met the same issue. And we also use the viewfs schema, could you please share your changes?

**Comment by everwind** [comment]
@alaleiwang  I met the same issue, could you please share your solutions. thx a lot
