### ISSUE TITLE
how to set multiple hdfs training data path

### ISSUE THREAD

**Issue by formath** [CNevd/Difacto_DMLC#5]
My hdfs data path is like this: `/root/${date}/part-*`

It will cause error when train_data written as blow examples:

```
1) /root/2016060*/part-*
2) /root/2016060[1-9]/part-*
3) /root/20160601/part-* /root/20160602/part-* ...
4) /root/20160601/part-*,/root/20160602/part-*, ...
```

So, how to set multiple hdfs training data path? Thanks.

**Comment by CNevd** [comment]
use `/root/2016060.*`    see match_file.h for details

**Comment by formath** [comment]
That works. Thanks
