### ISSUE TITLE
L1L2 has not effect on auc

### ISSUE THREAD

**Issue by formath** [CNevd/Difacto_DMLC#6]
I have tested L1 and L2 parameters ranged from 0.00 to 1000 and found that has no effect on the test auc anymore. Is there something incomplete in the code of the original project or I use it in a wrong way?

**Comment by CNevd** [comment]
@formath  test auc   do you mean val_data auc?

**Comment by formath** [comment]
@CNevd Yes. It has no visible difference when L1 and L2 ranged from 0 to 1000. Actually, I use the code forked from the original project. So, is there some bug fixed in this project against the original?

**Comment by CNevd** [comment]
there is no bug fixed about L1L2, 
pls 1. check is your config is lambda_l1 = xx  lambda_l2 = xx?
2. run local version to check the result
3. use ''' LOG(INFO) << w.w ''' to print w before and after penalty.Solve in [async_sgd.h](https://github.com/CNevd/Difacto_DMLC/blob/master/src/linear/async_sgd.h#L93)
