### ISSUE TITLE
Some confusion about use dump.cc to dump a readable model

### ISSUE THREAD

**Issue by Lisz1024** [CNevd/Difacto_DMLC#8]
I used the agaricus data to test dump.cc , and have dumped a readable model.
But the model's keys are very large such as 602879701896396800 , the train&test data's feature index only 0 to 120+ . 
So I confusing about what key's mean in the readable model? How can I match it with feature'index.

**Comment by CNevd** [comment]
the original id is reversed [here](https://github.com/CNevd/Difacto_DMLC/blob/36fd7dcb8cc0ed8173bcc07babd81a954dbef3cf/src/base/localizer.h#L121) in src/base/localizer.h,  try use `--max_key=xxx`  in the command if you know the max key of your data where `xxx` is a little greater than max key
eg:
max key is 125
use:

```
../../dmlc-core/tracker/dmlc_local.py -n 1 -s 1 build/difacto.dmlc guide/demo.conf --max_key=126
```

then it'll keep the original ids as the key

**Comment by Lisz1024** [comment]
@CNevd thank you very much.
it can work by set max_key use

```
../../dmlc-core/tracker/dmlc_local.py -n 1 -s 1 build/difacto.dmlc guide/demo.conf -max_key 126
```

In addition, I try to write a inverse function for `ReverseBytes` in dump.cc
It can work even if don't know max_key.

**Comment by CNevd** [comment]
@Lisz1024 great job!
