### ISSUE TITLE
Problem of reading data

### ISSUE THREAD

**Issue by XingLiu14-zz** [CNevd/Difacto_DMLC#9]
Hi there, I was testing the basic function of difacto on some simple data. The data format is libsvm, i.e. 10 1 2 3 5 (10 is value and rest are the feature ids).
But according to the dumped model I found it always missed some feature id, based on the data example I gave above, the model only has w and V for 1, 2 and 3, so 5 is missing.
Can someone give me some suggestions? Thanks!

**Comment by CNevd** [comment]
@XingLiu14 maybe w of id5 is 0 because of L1, so model will not save parameters of id5

**Comment by XingLiu14-zz** [comment]
I set both regularizers (l1 and l2) as 0.

**Comment by CNevd** [comment]
could you post run command and part of your dumped model ?

**Comment by XingLiu14-zz** [comment]
**configuration**:
train_data = "train_data" 
val_data = "test_data"
data_format = "libsvm"
model_out = "test_model"
embedding {
    dim = 3
    threshold = 0
    lambda_l2 = 0
    }
lambda_l1 = 0
early_stop = 0
lr_eta = 0.5
max_data_pass = 5
minibatch = 1

**data**  (I just made it up):
10 3 2 1
10 1 2 3

**launch script**:
`../../difacto/bin/dmlc_mesos.py -n 1 -s 1 -- ../../difacto/bin/difacto.dmlc train.conf --max_key 10`

**model**:
1       4       1.7558  -1.01184        1.72123 1.5805  20.9848
2       4       1.7558  -0.99882        1.71712 1.57912 20.9848

**Comment by CNevd** [comment]
hi I've checked the code, try to remove 
`Range<Key>(keys[0],keys[keys.size()-1]).To(msg.task.mutable_key_range());` in `ps-lite/src/kv/kv_cache.h`
see [commit 7ee13ba517a78d601576e5a79806e606afd9a58f](https://github.com/CNevd/Difacto_DMLC/commit/7ee13ba517a78d601576e5a79806e606afd9a58f)

**Comment by XingLiu14-zz** [comment]
It works well on the small data now. But when I was trying to use it on larger data, it still can't capture all the feature id (I have about 312k features, after one iteration the |w|=137k), and |w| and |V| will increase slowly with iteration goes (|w| increased to 227k after 5 iterations) which iteration number suppose not to affect dimension of model.

**Comment by CNevd** [comment]
@XingLiu14 that's strange, could you add  `key_cache=0` to your demo.conf and check again?
there is no such problems when i use agaricus.txt.train, and i will check it out using some larger datasets
Thanks

**Comment by XingLiu14-zz** [comment]
@CNevd I add `key_cache=0` to my configuration, didn't affect results.

I also checked agaricus.txt.train, mu results may be helpful for you:
**Config**:
`train_data = "../difacto/demo/agaricus.txt.train"`
`val_data = "../difacto/demo/agaricus.txt.test"`
`data_format = "libsvm"`
`model_out = "../difacto/demo/model"`
`embedding {`
`dim = 10`
`threshold = 1`
`lambda_l2 = 0.0001`
`}`
`lambda_l1 = 4`
`lr_eta = .01`
`max_data_pass = 3`
`minibatch = 500`
`early_stop = 1`
`key_cache = 0`

**Launch scripts**:
`../difacto/bin/dmlc_mesos.py -n 1 -s 1 ../difacto/bin/difacto.dmlc ../difacto/demo/train.conf`

**Output log**:
Connected 1 servers and 1 workers
Training: iter = 0
  sec   ttl #ex   inc #ex  |  |w|_0  logloss_w |   |V|_0    logloss    AUC
    1       6513  6.5e+03 |    111     0.6626   |    1130  0.65355  0.88112
Validating: iter = 0
  sec   ttl #ex   inc #ex  |  |w|_0  logloss_w |   |V|_0    logloss    AUC 
    2       8124  1.6e+03 |    111     0.5972   |    1130  0.48754  0.97258
Training: iter = 1
  sec   ttl #ex       inc #ex   |  |w|_0  logloss_w |   |V|_0    logloss    AUC
    3  1.464e+04  6.5e+03 |   116     0.5836     |   1160  0.41597  0.97334
Validating: iter = 1
  sec   ttl #ex        inc #ex |  |w|_0  logloss_w |   |V|_0    logloss    AUC
    4  1.625e+04  1.6e+03 |   116       0.5664 |    1160  0.35223  0.97591 
Training: iter = 2
  sec   ttl #ex        inc #ex |  |w|_0  logloss_w |   |V|_0    logloss    AUC
    5  2.276e+04  6.5e+03 |   117       0.5584 |    1170  0.32221  0.98434
Validating: iter = 2
  sec   ttl #ex        inc #ex |  |w|_0  logloss_w |   |V|_0    logloss    AUC
    6  2.437e+04  1.6e+03 |   117       0.5580 |    1170  0.29550  0.98570 
Hit max number of data passes 3
Saving the final model
Training is finished!

So we can see the |w| also increased from 111 to 117.

**Comment by CNevd** [comment]
@XingLiu14 when use V, the pred of a sample maybe large such as >35, then [py_[i]](https://github.com/CNevd/Difacto_DMLC/blob/master/src/difacto/loss.h#L108) maybe 0 1 or -1, so it's possible there are some features whose grad is always 0 when iter is small, you can check that just restrict py_[i] to a small scale

**Comment by XingLiu14-zz** [comment]
Hi, I've encountered more problems now, they all came from my large data:

1#: When I set threshold from 1 to 0, |V| increased significantly, does that mean many data didn't been read?

2#: When threshold=0, |w|*dim<|V|, but V will be 0 when correspond w is 0.

**Comment by CNevd** [comment]
1. check whether your data has many features that appear only once, if you set threshold=1 it meas if one feature appears more than once and w is not 0 it will has V which is initialized with rand(), what's more ttl #ex in the printed log is the total samples read
2. there is a parameter named `l1_shrk` which means `use or not use the contraint  V_i = 0 if  w_i = 0 . yes in default`

**Comment by XingLiu14-zz** [comment]
Just want to make sure, does |w| < (all features number) only indicate those missing features' gradient was 0 all the time so their w (which equals to 0) didn't been stored, any other reason makes |w| small? My major problem now is my RMSE over my data decreasing very slow and also |w| increasing slowly with iteration goes but can never reach total feature number. So I don't know which problem is the direct one that I should deal with now.

**Comment by CNevd** [comment]
yes you can check your weight by setting `l1_shrk=0  threshold=0` and save all the feature weights no matter w is 0 or not and look deep into it

**Comment by XingLiu14-zz** [comment]
Hi, I found when I set `l1_shrk=1` then dumped the model out, I still found some none zero V with zero w in the model.
And I still can't figure out why many features' weight remain 0 after several iterations since the differences of the output value always exist (RMSE always around 2), most of them should change after the first iteration, the fact is the number of nonzero weights increase slowly with iteration goes.

**Comment by CNevd** [comment]
@XingLiu14  Could you sent me ur train data? will check that for u, my email:  wangyalong20@gmail.com

**Comment by XingLiu14-zz** [comment]
@CNevd Email sent, thank you

**Comment by XingLiu14-zz** [comment]
So the default lambda_l1 for w is 1, I thought the regularizers will been set 0 automatically. I only set lambda_l2 in my config results in many 0 weights. Problem solved now, thank you.
